### ISSUE TITLE
Release of ghc-9.6 ready version on hackage?

### ISSUE THREAD

**Issue by alaendle** [EventStore/EventStoreDB-Client-Haskell#8]
Just asking because we still have the package disabled on stackage nightly build.

"Yorick Laupa yo.eight@gmail.com @YoEight":
        - eventstore < 0 # 1.4.3 https://github.com/commercialhaskell/stackage/issues/7075

So I guess a new release should be made to be able to re-enable the package - or we could remove the package entirely from the build-constraints file.

**Comment by YoEight** [comment]
Hey @alaendle, thanks for reaching out. I think it's safe for you to remove the package entirely. I wasn't able to keep up with all the changes that stackage asked a couple of years ago. Mostly likely, I'm going to build with Nix.
